apps/book/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views
from .views import BookHomeRedirectView, BookHomeListView, BookDetailView, BookCreateView, BookDeleteView, BookUpdateView, ReviewListView


urlpatterns = [

    url(r'^$', BookHomeListView.as_view(), name="book-home"),
    url(r'^(?P<pk>\d+)/$', BookDetailView.as_view(), name="book-detail"),
    url(r'^create/$', BookCreateView.as_view(), name="book-create"),
    url(r'^delete/(?P<pk>\d+)/$', BookDeleteView.as_view(), name="book-delete"),
    url(r'^update/(?P<pk>\d+)/$', BookUpdateView.as_view(), name="book-update"),
    url(r'^signup/$', views.SignupView.as_view(), name='signup'),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
    url(r'^review/$',  ReviewListView.as_view(), name="review"),

]

bookreview/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('apps.book.urls')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^admin/', admin.site.urls),
]

apps/book/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse

# Create your models here.
class Book(models.Model):
    title = models.CharField(max_length=200)
    author = models.CharField(max_length=200)
    added_by = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated_at = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('book-detail', kwargs={'pk':self.id})

class Review(models.Model):
    creator = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.ForeignKey(Book, on_delete=models.CASCADE)
    review = models.TextField(max_length=1000)
    rating = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated_at = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return self.name

apps/book/forms.py
from django.forms import ModelForm
# from django.forms.models import inlineformset_factory

from .models import Book, Review

class BookForm(ModelForm):

    class Meta:
        model = Book
        fields = ['title', 'author']

class ReviewForm(ModelForm):
    class Meta:
        model = Review
        fields = ['review', 'rating']

apps/book/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth import login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.core.urlresolvers import reverse_lazy
from django.core.urlresolvers import reverse
from django.views import View
from django.views.generic import FormView, RedirectView, CreateView, ListView, DetailView, DeleteView, UpdateView, FormView
from django.views.generic.detail import SingleObjectMixin

from .models import Book, Review
from .forms import BookForm, ReviewForm

# Create your views here.
class LoginView(FormView):
    form_class = AuthenticationForm
    success_url = reverse_lazy('book-home')
    template_name = "accounts/login.html"

    def get_form(self, form_class=None):
        if form_class is None:
            form_class = self.get_form_class()
        return form_class(self.request, **self.get_form_kwargs())

    def form_valid(self, form):
        login(self.request, form.get_user())
        return super().form_valid(form)

class LogoutView(RedirectView):
    url = reverse_lazy('book-home')

    def get(self, request, *args, **kwargs):
        logout(request)
        return super(LogoutView, self).get(request, *args, **kwargs)

class SignupView(CreateView):
    form_class = UserCreationForm
    success_url = '/accounts/login/'
    template_name = "registration/signup.html"


class BookHomeListView(ListView):
    context_object_name = 'books'
    fields = ('title', 'added_by', 'created_at')
    model = Book
    template_name = "book/book_home.html"

class BookHomeRedirectView(RedirectView):
    url = reverse_lazy('book-home')

class BookDisplay(DetailView):
    template_name = "book/book.html"
    model = Book

    def get_context_data(self, **kwargs):
        context = super(BookDisplay, self).get_context_data(**kwargs)
        context['form'] = ReviewForm()
        return context

class Review(SingleObjectMixin, FormView):
    template_name = 'single_form.html'
    form_class = ReviewForm
    model = Book

    def post(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return HttpResponseForbidden()
        self.object = self.get_object()
        return super(Review, self).post(request, *args, **kwargs)

    def form_valid(self, form):
        form.instance.title_id = self.kwargs.get('pk')
        form.instance.creator = self.request.user
        return super(Review, self).form_valid(form)

    def get_success_url(self):
        return reverse('book-detail', kwargs={'pk': self.object.pk})

class BookDetailView(View):
    def query_set(self):
        return Book.objects.all()

    def get(self, request, *args, **kwargs):
        view = BookDisplay.as_view()
        return view(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        view = Review.as_view()
        return view(request, *args, **kwargs)

class BookCreateView(LoginRequiredMixin, CreateView):
    template_name = "book/book_create.html"
    fields = ('title', 'author')
    model = Book

    def form_valid(self, form):
        form.instance.added_by = self.request.user
        return super(BookCreateView, self).form_valid(form)

class BookDeleteView(LoginRequiredMixin, DeleteView):
    model = Book
    success_url = reverse_lazy('book-home')

class BookUpdateView(LoginRequiredMixin, UpdateView):
    template_name = "book/book_update.html"
    model = Book
    form_class = BookForm

class ReviewListView(ListView):
    template_name = "review.html"
    model = Review

apps/book/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Book Review</title>

    <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"></link>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.7/css/materialize.min.css"></link>

    <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.7/js/materialize.min.js"></script>
</head>

<body>
    <nav class="black">
        <div class="nav-wrapper conatiner">
            <a href="#" class="brand-logo">Book Review</a>
            <ul id="nav-mobile" class="right hide-on-med-and-down">
                {% if user.is_authenticated %}
                <li><a href="{% url 'logout' %}">Sign Out</a></li>
                {% else %}
                <li><a href="{% url 'login' %}">Sign In</a></li>
                <li><a href="{% url 'signup' %}">Sign Up</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>
<div class="container">
    {% block container %}
    {% endblock %}
</div>
</body>

</html>

apps/book/templates/book/2.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Book Review</title>

    <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"></link>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.7/css/materialize.min.css"></link>

    <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.7/js/materialize.min.js"></script>
</head>

<body>
<div class="container">
    {% block container %}
    {% endblock %}
</div>
</body>

</html>

apps/book/templates/book/book.html
{% extends 'base.html' %}

{% block container %}
  <h2 class="title">{{book.title}}</h2>
  <div class="card">
    <div class="card-content">
      <p class=""><i>{{book.title}}</i></p>
      <hr>
      {{book.author | safe}}
    </div>
    <div class="card-action">
      <a class="btn-flat" href="{% url 'book-home' %}">Book Home</a>
      <form class="right" method="POST" action="{% url 'book-delete' book.id %}">
         {% csrf_token %}<input class="btn red darken-2" type="submit" value="DELETE">
      </form>
      <a class="btn-flat right" href="{% url 'book-update' book.id %}">Update</a>
    </div>
  </div>
  <hr>
{% include "single_form.html" with form=form%}
  <hr>
  {% for book in book_list %}
      <ul>
          <li>{{ book.title }}</li>
          {% for review in book.review_set.all %}
              <li>{{ review }}</li>
          {% endfor %}
      </ul>
  {% endfor %}

  {% endblock %}

apps/book/templates/book/book_create.html
{% extends 'base.html' %}

{% block container %}
  <h3 class="title">Create New Book</h3>
  <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <input class="btn" type="submit" value="Create" />
  </form>
{% endblock %}

apps/book/templates/book/book_home.html
{% extends 'base.html' %}

{% block container %}
  <h3 class="title">All Books</h3>
  <div class="collection">
    {% for book in books %}
        <a class="collection-item" href="{% url 'book-detail' book.id %}">{{book.title}}</a>
    {% endfor %}
  </div>
  <a class="btn right" href="{% url 'book-create' %}">Create Book</a>
{% endblock %}

apps/book/templates/book/book_update.html
{% extends 'base.html' %}

{% block container %}
  <h3 class="title">Update {{book.title}}</h3>
  <form class="card" method="post">
    <div class="card-content">
      {% csrf_token %}
      {{ form.as_p }}
    </div>
    <div class="card-action">
      <a class="btn-flat" href="{{ book.get_absolute_url }}">Cancel</a>
      <input class="btn" type="submit" value="Update" />
    </div>
  </form>
{% endblock %}

apps/book/templates/review.html
{% extends 'base.html' %}

{% block container %}
  <h3 class="title">All Reviews</h3>
  <div class="collection">
      {% for book in object_list %}
          Name:
          {% for review in book.review_set.all %}
              {{ review.review }}
          {% empty %}
             None
          {% endfor %}
      {% endfor %}
{% endblock %}

apps/book/templates/single_form.html
<form method='POST' action=''>{% csrf_token %}
{{ form }}
<input class='btn' type='submit' value='Add Review' />